language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
env:
  - RAILS=4.2.11.1
  - RAILS=5.2.3
matrix:
  exclude:
before_install:
  - sudo apt install -y gnupg gnupg2
cache: bundler
dist: xenial
addons:
  apt:
    update: true

